<a href="https://colab.research.google.com/github/Shrutithakur30/UCS420/blob/main/assign4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1** Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**a)** Addition of 2 in all the element

In [ ]:
add = arr+2
print(add)

[3 4 5 6 7]


b) Multiply 3 with all the elements

In [ ]:
multiply = arr*3
print(multiply)

[ 3  6  9 12 15]


c) Divide every element by 2

In [ ]:
div = arr/2
print(div)

[0.5 1.  1.5 2.  2.5]


**Q2** Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5,6])
np.flip(arr,axis=0)

array([6, 5, 4, 3, 2, 1])

b) Find the most frequent value and their indice(s) in the following arrays

In [ ]:
x= np.array([1,2,3,4,5,1,2,1,1,1])
print(np.bincount(x).argmax())

1


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(np.bincount(y).argmax())

1


**Q3** For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


a) Access 1st row, 2nd column

In [ ]:
arr[0][1]

20

b) Access 3rd row, 1st column

In [ ]:
arr[2][0]

70

**Q4** Write program to create an 1-D NumPy array named <> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [ ]:
shruti=np.array(np.linspace(10,100,num=25))
print(shruti)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
print("dimension of the array:",shruti.ndim)

dimension of the array: 1


In [ ]:
print("shape of the array:",shruti.shape)

shape of the array: (25,)


In [ ]:
print("total elements of the array:",np.size(shruti))

total elements of the array: 25


In [ ]:
print("data type of each element",shruti.dtype)

data type of each element float64


In [ ]:
print("total bytes of array :",shruti.nbytes)

total bytes of array : 200


In [ ]:
shruti.reshape(25,1)

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [ ]:
print("before transpose :")
print(shruti)
print("transposed array :")
print(shruti.T) #.T has no effect for 1D array

before transpose :
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
transposed array :
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


**Q5** Create a 2-D Array of three rows and four columns, named ucs420_shruti> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_shruti>. Resize the array to two rows and three columns and name it as resized_ ucs420_shruti>

In [ ]:
ucs420_shruti=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
ucs420_shruti

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [ ]:
mean=np.mean(ucs420_shruti)
print("mean of array :",mean)

mean of array : 43.333333333333336


In [ ]:
median=np.median(ucs420_shruti)
print("median of array :",median)

median of array : 37.5


In [ ]:
unique_elements=np.unique(ucs420_shruti)
print(unique_elements)

[10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
maxArr=ucs420_shruti.max()
print("max. element in array :",maxArr)

max. element in array : 90


In [ ]:
minArr=ucs420_shruti.min()
print("min. element in array :",minArr)

min. element in array : 10


In [ ]:
reshaped_ucs420_shruti=ucs420_shruti.reshape(4,3)
print(reshaped_ucs420_shruti)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [ ]:
resized_ucs420_shruti=np.resize(ucs420_shruti,(2,3))
resized_ucs420_shruti

array([[10, 20, 30],
       [40, 50, 60]])